### ISSUE TITLE
[Feature Request] Add `on_inference_ready` callback to llm-engine deployments via `Model.create`

### ISSUE THREAD

**Issue by jenkspt** [scaleapi/llm-engine#193]
This is a feature request to add an `on_inference_ready` callback to `Model.create`, which sends a GET request to the provided endpoint when the deployed model is ready for inference.

**Comment by ian-scale** [comment]
This should now be addressed because you can call `Model.get()` and one of the response fields will get the status of the model as an enum. You should get back the response `ModelEndpointStatus.READY` when the model is ready for inference, i.e. something like: 

`if Model.get(model_name).status.name == "READY":` 

Feel free to look at this doc for more details https://llm-engine.scale.com/guides/endpoint_creation/. @jenkspt let me know if there's anything else still missing for this to get closed out.
